#!bin/sh

## Colorized ls
alias ls="ls -G"

## List process with pid + command
alias pso="ps -e -opid,cmd"

## Django stuff
alias dj="python manage.py"
alias djr="dj runserver"
alias djrp="dj runserver_plus"
alias djsm="dj schemamigration --auto"
alias djmg="dj migrate"
alias djpyc="dj clean_pyc"
